title: Pius Tech & Dev RnD
email: hwanpiusjoon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://piusai.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: "PIUS : Combat & Engine Lab" # add your name
author-pic: Pius-Logo.jpg
about-author: " C++ 기반 로직 설계와 엔진 구조에 대한 기술 블로그 입니다."

# Contact links
email: hwangpiusjoon@gmail.com # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: hwangpiusjoon # Add your Linkedin handle
github: piusAI # Add your Github handle
twitter: '' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
