# ================================
# Site Settings
# ================================

remote_theme: mmistakes/so-simple-theme

skin: "/assets/css/skins/default.css"
locale: "ko-KR"

title: "piusAi"
description: "Graphics Programming / Unreal Engine / Combat System Architecture"

url: "https://piusai.github.io"
baseurl: ""

logo: "/assets/img/pius-icon.png"

date_format: "%Y.%m.%d"

read_time: true
words_per_minute: 220

# ================================
# Math
# ================================

mathjax:
  enable: true

# ================================
# Fonts
# ================================

google_fonts:
  - name: "Pretendard"
    weights: "400,500,700"
  - name: "JetBrains Mono"
    weights: "400,700"

# ================================
# SEO / Analytics
# ================================

google_analytics:

twitter:
  username: piusAi

# ================================
# Liquid
# ================================

liquid:
  error_mode: strict

# ================================
# Build
# ================================

future: true
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
markdown: kramdown

feed:
  path: atom.xml

paginate: 5
paginate_path: /page:num/

search_full_content: true

# ================================
# Archive
# ================================

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# ================================
# Plugins
# ================================

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# ================================
# Defaults
# ================================

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: true
      toc: true
      toc_sticky: true

# ================================
# Author
# ================================

author:
  name: "piusAi"
  picture: "/assets/img/pius-icon.png"
  email:
  bio: "Graphics Programmer / Combat Programmer / Engine Architecture"

  links:
    - title: GitHub
      url: https://github.com/piusAI
      icon: fab fa-github-square

    - title: YouTube
      url: https://www.youtube.com/@h0wju
      icon: fab fa-youtube

# ================================
# Footer
# ================================

footer_links:
  - title: GitHub
    url: https://github.com/piusAI
    icon: fab fa-github-square

  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
